language: go
go:
  - 1.11.x
sudo: false
install:
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export GO111MODULE=on
  - (cd cmd/dcrtime && go build)
  - (cd cmd/dcrtime_dumpdb && go build)
  - (cd cmd/dcrtime_timestamp && go build)
  - (cd cmd/dcrtime_unflush && go build)
  - (cd dcrtimed && go build)
  - ./goclean.sh
