
[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-flags"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/decred/dcrd"
  version = "1.2.0"

[[constraint]]
  name = "github.com/decred/dcrwallet"
  version = "1.1.0"

[[constraint]]
  name = "github.com/decred/slog"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/jrick/logrotate"
  version = "1.0.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[prune]
  go-tests = true
  unused-packages = true
